language: go

os:
  - linux
  - osx

go:
  - 1.6
  - 1.8

matrix:
  exclude:
  - os: osx
    go: 1.6

install:
  - git submodule update --init --recursive
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./make.bash libax25; fi

script:
  - ./make.bash
